---
  - name: docker swarm infrastructure
    hosts: all
    remote_user: root
    vars_files:
      - vars/main.yml
    roles:
      - common
      - swarm

  - name: docker manager traefik
    hosts: manager
    remote_user: root
    roles:
      - traefik
