---
- name: Init swarm mode
  docker_swarm:
    state: present
    advertise_addr: "{{ swarm_advertise_addr }}"

- name: Create docker ingress network
  docker_network:
    name: ingress
    driver: overlay
